version: '3'
services:
 nginx:
   image: nginx:latest
   ports:
     - 8080:80
   volumes:
     - ./app/views/
   depends_on:
     - php
 php:
   build: ./docker-app
   volumes:
     - ./app/views/
   depends_on:
     - db
 db:
   image: mysql:8.0.21
   ports:
     - 13306:3306
   volumes:
     - ./mysql:/var/lib/mysql
   environment:
     MYSQL_ROOT_PASSWORD: secret
 phpmyadmin:
   image: phpmyadmin/phpmyadmin:latest
   ports:
     - 8888:80
   depends_on:
     - db